### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by abique** [revec/llvm-revec#1]
Hi,

I think the idea is amazing!
What is the current status?
Did you manage to finish your pass?
Did LLVM reject the idea?

Regards,
Alex

**Comment by ajayjain** [comment]
Hi @abique, we didn't submit the compiler pass upstream to the LLVM project, so they haven't rejected it. This repository contains companion code for our Compiler Construction 2019 paper, https://arxiv.org/abs/1902.02816, and can be used instead of the official LLVM following the compilation instructions in our README. However, it's currently unmaintained and hasn't received recent updates.
